<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <RootNamespace>Axis.Rhae.Contract</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Axis.Dia.Core" Version="0.0.6" />
    <PackageReference Include="Axis.Dia.PathQuery" Version="0.0.6" />
    <PackageReference Include="Axis.Luna.Unions" Version="7.0.10" />
    <PackageReference Include="Semver" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Utils\" />
  </ItemGroup>

</Project>
